name: Ticketing-Issues

on:
  issues:
    types: [ labeled ]

jobs:
  # This workflow contains a single job called "build"
  Move_Labeled_Issue_On_Project_Board:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Labeled-issue
      - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        with: 
          action-token: "${{ secrets.lightToken }}"
          project-url: "https://github.com/Battlelegend/Test/projects/1"
          column-name: "To do"
          label-name: "ticket-shop"
         
